### PR TITLE
KiCad7 & Python3 fixes

### PR DESCRIPTION
**Pull request by mmuman**
It seems to run fine now, but I suspect it's missing some newly added fields.

### CODE REVIEW

**Comment by devbisme** [comment]
I created a new branch called `development` that incorporates your changes. I made a few more to correct for changes in `pcbnew`. I got 2 of the 4 `pytest` unit tests to pass. One current problem is that `BOARD` objects no longer have a `SetDesignSettings()` method although they still have a `GetDesignSettings()` method. I don't know why it was removed or if there is some other technique for updating the board settings. It would take some research to find out.

The question is whether it's worth it. The KiCad dev team has already stated that they would be changing `pcbnew` for the forseeable future, so it would require continual tracking to stay in sync. But if you want to keep at it, just make changes to the `development` branch and we'll go from there.

**Comment by mmuman** [comment]
I initially wanted to make a plugin to select manufacturer presets and set values that would be suitable to all the selected, because I didn't want to have to redesign a board to change manufacturer. I already got a GUI that loads values from files:
Screenshot_20231129_052657

So I think there would be some more use cases…

I think for the fields at least we could use `dir()` or some other way to automate building the list so added fields wouldn't be a problem. For the rest I guess we'll have to see. I still see [SetDesignSettings](https://gitlab.com/kicad/code/kicad/-/blob/2758acfd4265f295c14a5bf009fa742e4abad131/pcbnew/class_board.h#L550) in the source, maybe SWIG missed it, or it's been disabled as an export?

**Comment by devbisme** [comment]
If you want to move forward and make `kinjector` work with KiCad 7.0, then I'll support you all I can.

As for `SetDesignSettings()`, the link you provided goes to the `master` branch. I checked in the `7.0` branch and the function is missing (in fact, the `class_board.h` file is no longer there). It also threw an exception when I ran the `kinjector` pytests. You might check in the Python prompt on your installation of KiCad to see if `BOARD` objects still have the `SetDesignSettings()` attribute. Maybe we're out of sync?

**Comment by devbisme** [comment]
OK, I'll leave the your changes and mine in the development branch if you decide you want to proceed further.

**Pull request closed without merging**
