### PR TITLE
2to3-2.7 -w *.py

### LINKED ISSUE #2: Some project files aren't Python 3-ready
I'm fixing this now.

### PR DESCRIPTION
**Pull request by sowbug**
Fixes #2 by running `2to3` over all the Python files I could find. I haven't extensively tested, but it did stop the errors I was having.

### CODE REVIEW

**Comment by sowbug** [comment]
Also now fixes #1 by resetting file pointer following the example in earlier parts of the existing code.

**Comment by xesscorp** [comment]
Thanks for diagnosing the problem and making the PR!

Running `2to3` fixed the Python3 problems in `cli.py`, but it made a bunch of unnecessary changes in `kinjector.py` so I kept the original version. I uploaded the files to the [fix branch](https://github.com/xesscorp/kinjector/tree/fix). Give it a try. If it still fixes your problems, then I'll move it to master and release version 0.0.6.

**Comment by sowbug** [comment]
The fix branch successfully handles the Python 3 syntax errors, but my attempt to fix the other bug with https://github.com/xesscorp/kinjector/pull/3/commits/6ad35b76cdccd50c49ad14d9385a7040a896fa83 is not working. You could merge the whole thing back to master because it's not a regression, but you might want to hold off while I have a look why it's still broken. Looking now.

**Comment by sowbug** [comment]
Ugh, I have a fix but don't understand why it works. Replace `yaml.load()` with `yaml.safe_load()` and it successfully raises an exception. Otherwise the loader happily passes through the KiCad PCB file contents as if they were valid YAML.

It's up to you whether to take that suggestion. It does fix it.

**Comment by xesscorp** [comment]
I tried your fix with using `safe_load()`, but it didn't seem to work for me.

Then I tried passing a KiCad board file to an [online YAML linter](http://www.yamllint.com/), and it was accepted as valid YAML! So getting an exception from the `yaml.load()` function may not be the way to go. I found that when a board file is passed to `yaml.load()`, it returns a string object containing the contents of the entire file. So I modified the code to only accept the file as YAML if `yaml.load()` returns a `dict()` object. That seems to work (for me).

You can give it a try if you like. It's in the [fix branch](https://github.com/xesscorp/kinjector/tree/fix).

**Comment by sowbug** [comment]
Looking for an empty result was going to be my next approach, but I wanted to try to preserve as much of the original code flow as possible. Oh well!

Just tested locally, and it properly fails to fail. Note that I haven't verified whether YAML is parsed or written, since my own workflow uses JSON. So if you can verify that the YAML path hasn't broken, then we should be good to go. Thanks for sticking with this issue and getting it resolved!

**Comment by xesscorp** [comment]
I verified the YAML path was working in my environment. I've released version 0.0.6 on Github and PyPi.

> Thanks for sticking with this issue and getting it resolved!

No problem. Thanks for using Kinjector.

**Pull request closed without merging**
